name: Deploy to Azure

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v2
        with:
         client-id: 
         tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_B9005449F5E44F66BCFC171B4887AF86 }}
         subscription-id: aab31954-beba-43f7-b2c2-141f2a4667f6

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: GymWebApp
          package: .
